api:
  - changed-files:
      - any-glob-to-any-file:
          - "frontend/src/ts/ape/**/*"
          - "backend/src/api/**/*"

assets:
  - all:
      - changed-files:
          - any-glob-to-any-file: "frontend/static/**/*"
          - all-globs-to-all-files: "!frontend/static/**/*.html"

backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**/*"

docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**/*"

packages:
  - changed-files:
      - any-glob-to-any-file: "packages/**/*"

"local dev":
  - changed-files:
      - any-glob-to-any-file:
          - "**/turbo.json"
          - "**/tsconfig.json"
          - "**/knip.json"
          - "**/.prettierrc.json"
          - "**/.oxlintrc.json"
