sonar.projectKey=monkeytype
sonar.projectName=Monkeytype
sonar.projectVersion=26.15.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_1efa4508047307308d66aebca69d97faefddbdf8

sonar.sources=frontend/src,backend/src,packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/.turbo/**,**/build/**,**/*.min.js,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.node.maxspace=4096

sonar.sourceEncoding=UTF-8
