const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const configSchema = new Schema({
  theme: { type: String },
  customTheme: Boolean,
  customThemeColors: [{ type: String }],
  favThemes: [{ type: String }],
  showKeyTips: Boolean,
  showLiveWpm: Boolean,
  showTimerProgress: Boolean,
  smoothCaret: Boolean,
  quickTab: Boolean,
  punctuation: Boolean,
  numbers: Boolean,
  words: Number,
  time: Number,
  mode: String,
  quoteLength: [{ type: Number }], //not sure why this is an array
  language: String,
  fontSize: Number,
  freedomMode: Boolean,
  difficulty: String,
  blindMode: Boolean,
  quickEnd: Boolean,
  caretStyle: String,
  paceCaretStyle: String,
  flipTestColors: Boolean,
  capsLockBackspace: Boolean,
  layout: String,
  confidenceMode: String,
  indicateTypos: Boolean,
  timerStyle: String,
  colorfulMode: Boolean,
  randomTheme: String, //feels like this should be a boolean
  timerColor: String,
  timerOpacity: String, //maybe should be a number
  stopOnError: String,
  showAllLines: Boolean,
  keymapMode: String,
  keymapStyle: String,
  keymapLegendStyle: String,
  keymapLayout: String,
  fontFamily: String,
  smoothLineScroll: Boolean,
  alwaysShowDecimalPlaces: Boolean,
  alwaysShowWordsHistory: Boolean,
  singleListCommandLine: String,
  playSoundOnError: Boolean,
  playSoundOnClick: String,
  startGraphsAtZero: Boolean,
  swapEscAndTab: Boolean,
  showOutOfFocusWarning: Boolean,
  paceCaret: String,
  paceCaretCustomSpeed: Number,
  pageWidth: String,
  chartAccuracy: Boolean,
  chartStyle: String,
  minWpm: String,
  minWpmCustomSpeed: Number,
  highlightMode: String,
  alwaysShowCPM: Boolean,
  enableAds: String,
  hideExtraLetters: Boolean,
  strictSpace: Boolean,
  minAcc: String,
  minAccCustom: Number,
  showLiveAcc: Boolean,
  monkey: Boolean,
  repeatQuotes: String,
  oppositeShiftMode: String,
  customBackground: String,
  customBackgroundSize: String,
  customBackgroundFilter: [{ type: Number }],
  customLayoutfluid: String,
});

module.exports = { configSchema };
