import { Challenge, ChallengeName } from "@monkeytype/schemas/challenges";

export const Challenges: Record<ChallengeName, Omit<Challenge, "name">> = {
  "100hours": {
    display: "100 hours",
    autoRole: false,
    type: "hidden",
    discordRoleId: "761766710704603166",
    category: "otherChallenges",
    description: "Achieve 100 hours of typing.",
    parameters: [],
  },
  "250hours": {
    display: "250 hours",
    autoRole: false,
    type: "hidden",
    discordRoleId: "799825381733433344",
    category: "otherChallenges",
    description: "Achieve 250 hours of typing.",
    parameters: [],
  },
  "500hours": {
    display: "500 hours",
    autoRole: false,
    type: "hidden",
    discordRoleId: "951861792622125106",
    category: "otherChallenges",
    description: "Achieve 500 hours of typing.",
    parameters: [],
  },
  "1000hours": {
    display: "1000 hours",
    autoRole: false,
    type: "hidden",
    discordRoleId: "1262175323588395100",
    category: "otherChallenges",
    description: "Achieve 1000 hours of typing.",
    parameters: [],
  },
  "69": {
    display: "6969696969",
    autoRole: true,
    type: "customTime",
    parameters: [69],
    message:
      "You need to achieve 69 wpm, 69 raw, 69% accuracy and 69% consistency.",
    requirements: {
      wpm: { exact: 69 },
      raw: { exact: 69 },
      acc: { exact: 69 },
      con: { exact: 69 },
    },
    discordRoleId: "749505965174292511",
    category: "otherChallenges",
    description: "Complete a 69-second test and achieve 69 WPM, 69 raw, 69% accuracy, and 69% consistency.",
  },
  oneHourWarrior: {
    display: "One Hour Warrior",
    autoRole: true,
    type: "customTime",
    parameters: [3600],
    requirements: {
      time: { min: 3600 },
    },
    discordRoleId: "728371749737201855",
    category: "classicEndurance",
    description: "Complete a one-hour test.",
  },
  doubleDown: {
    display: "Double Down",
    autoRole: true,
    type: "customTime",
    parameters: [7200],
    requirements: {
      time: { min: 7200 },
    },
    discordRoleId: "732008008514535544",
    category: "classicEndurance",
    description: "Complete a two-hour test.",
  },
  tripleTrouble: {
    display: "Triple Trouble",
    autoRole: true,
    type: "customTime",
    parameters: [10800],
    requirements: {
      time: { min: 10800 },
    },
    discordRoleId: "732008047618293762",
    category: "classicEndurance",
    description: "Complete a three-hour test.",
  },
  quad: {
    display: "Quaaaaad",
    autoRole: true,
    type: "customTime",
    parameters: [14400],
    requirements: {
      time: { min: 14400 },
    },
    discordRoleId: "736215666352455801",
    category: "classicEndurance",
    description: "Complete a four-hour test.",
  },
  "8Ball": {
    display: "8 Ball",
    type: "customTime",
    parameters: [28800],
    requirements: {
      time: { min: 28800 },
    },
    discordRoleId: "736528159956271126",
    category: "classicEndurance",
    description: "Complete an eight-hour test.",
  },
  theBig12: {
    display: "The Big 12",
    type: "customTime",
    parameters: [43200],
    requirements: {
      time: { min: 43200 },
    },
    discordRoleId: "740532256388546581",
    category: "classicEndurance",
    description: "Complete a twelve-hour test.",
  },
  "1Day": {
    display: "1 Day",
    type: "customTime",
    parameters: [86400],
    requirements: {
      time: { min: 86400 },
    },
    discordRoleId: "751801958511149057",
    category: "classicEndurance",
    description: "Complete a twenty-four-hour test.",
  },
  trueSimp: {
    display: "True Simp",
    autoRole: true,
    type: "customText",
    parameters: ["miodec", "repeat", 10000, "word", false],
    discordRoleId: "744328648211038359",
    category: "specificText",
    description: "Type miodec ten thousand times.",
  },
  bigramSalad: {
    display: "Bigram Salad",
    autoRole: true,
    type: "customText",
    parameters: [
      "to of in it is as at be we he so on an or do if up by my go",
      "random",
      100,
      "word",
      false,
    ],
    requirements: {
      wpm: { min: 100 },
    },
    discordRoleId: "818535054145093652",
    category: "speed",
    description: "Get 100 WPM on a randomized, 100-word custom test with the words list: to of in it is as at be we he so on an or do if up by my go.",
  },
  simp: {
    display: "Simp",
    autoRole: true,
    type: "customText",
    parameters: ["miodec", "repeat", 1000, "word", false],
    discordRoleId: "743854992699687023",
    category: "specificText",
    description: "Type miodec one thousand times.",
  },
  simpLord: {
    display: "Simp Lord",
    // false for now
    autoRole: false,
    type: "customText",
    // this would be 100k times:
    parameters: ["miodec", "repeat", 100000, "word", false],
    discordRoleId: "984911956949479445",
    category: "specificText",
    description: "Type miodec one hundred thousand times.",
  },
  antidiseWhat: {
    display: "Antidise-what?",
    autoRole: true,
    type: "customText",
    parameters: ["antidisestablishmentarianism", "repeat", 1, "word", false],
    requirements: {
      wpm: { min: 200 },
    },
    discordRoleId: "782006507360616449",
    category: "specificText",
    description: "Get at least 200 wpm typing antidisestablishmentarianism.",
  },
  whatsThisWebsiteCalledAgain: {
    display: "What's this website called again?",
    autoRole: true,
    type: "customText",
    parameters: ["monkeytype", "repeat", 1000, "word", false],
    discordRoleId: "739276161603076116",
    category: "specificText",
    description: "Type monkeytype one thousand times.",
  },
  developd: {
    display: "Develop'd",
    autoRole: true,
    type: "customText",
    parameters: ["develop", "repeat", 1000, "word", false],
    discordRoleId: "735964917877964932",
    category: "specificText",
    description: "Type develop one thousand times.",
  },
  slowAndSteady: {
    display: "Slow and Steady",
    autoRole: true,
    type: "customTime",
    parameters: [300],
    requirements: {
      wpm: { exact: 60 },
      config: { liveSpeedStyle: "off", paceCaret: "off" },
    },
    discordRoleId: "782005061935956008",
    category: "speed",
    description: "Complete a 5-minute test with exactly 60 WPM without using the live WPM or pace caret.",
  },
  speedSpacer: {
    display: "Speed Spacer",
    autoRole: true,
    type: "customText",
    parameters: [
      "a b c d e f g h i j k l m n o p q r s t u v w x y z",
      "random",
      100,
      "word",
      false,
    ],
    requirements: {
      wpm: { min: 100 },
    },
    discordRoleId: "755244049446731856",
    category: "speed",
    description: "Get 100 wpm on a randomised custom test with the input: a b c d e f g h i j k l m n o p q r s t u v w x y z (the alphabet) and a word count of 100.",
  },
  iveGotThePower: {
    display: "I've got the POWER",
    autoRole: true,
    type: "customText",
    parameters: ["power", "repeat", 10, "word", false],
    requirements: {
      wpm: { min: 400 },
    },
    discordRoleId: "764879734873915402",
    category: "speed",
    description: "Get 400 WPM while typing power 10 times.",
  },
  accuracyExpert: {
    display: "Accuracy Expert",
    autoRole: true,
    type: "accuracy",
    parameters: [],
    message: "Minimum 60wpm and 100% accuracy required.",
    requirements: {
      wpm: { min: 60 },
      acc: { exact: 100 },
      afk: { max: 5 },
      time: { min: 600 },
    },
    discordRoleId: "751168451263070259",
    category: "accuracy",
    description: "Complete a 10-minute Master mode test.",
  },
  accuracyMaster: {
    display: "Accuracy Master",
    autoRole: true,
    type: "accuracy",
    parameters: [],
    message: "Minimum 60wpm and 100% accuracy required.",
    requirements: {
      wpm: { min: 60 },
      acc: { exact: 100 },
      afk: { max: 5 },
      time: { min: 1200 },
    },
    discordRoleId: "751168567432708239",
    category: "accuracy",
    description: "Complete a 20-minute Master mode test.",
  },
  accuracyGod: {
    display: "Accuracy God",
    autoRole: true,
    type: "accuracy",
    parameters: [],
    message: "Minimum 60wpm and 100% accuracy required.",
    requirements: {
      wpm: { min: 60 },
      acc: { exact: 100 },
      afk: { max: 5 },
      time: { min: 1800 },
    },
    discordRoleId: "751168657626890361",
    category: "accuracy",
    description: "Complete a 30-minute Master mode test.",
  },
  inAGalaxyFarFarAway: {
    display: "In a galaxy far, far away",
    type: "script",
    parameters: ["episode4.txt", null, ["space_balls"]],
    requirements: {
      config: { tapeMode: "off" },
    },
    discordRoleId: "740004324301602907",
    category: "scriptsOrSongs",
    description: "Type out the entire Star Wars Episode 4 script with punctuation while watching the movie simultaneously.",
  },
  beepBoop: {
    display: "Beep Boop",
    type: "script",
    parameters: ["beepboop.txt", null, ["nospace"]],
    message: "Mininum 45 WPM and 100% accuracy required.",
    requirements: {
      wpm: { min: 45 },
      acc: { min: 100 },
      funbox: { exact: ["nospace"] },
    },
    discordRoleId: "813076265145729024",
    category: "scriptsOrSongs",
    description: "Type the beepboop script with 100% accuracy and at least 45 WPM.",
  },
  whosYourDaddy: {
    display: "Who's your daddy",
    type: "script",
    parameters: ["episode5.txt", null, ["space_balls"]],
    requirements: {
      config: { tapeMode: "off" },
    },
    discordRoleId: "742171915405361204",
    category: "scriptsOrSongs",
    description: "Type out the entire Star Wars Episode 5 script with punctuation while watching the movie simultaneously.",
  },
  itsATrap: {
    display: "It's a trap!!",
    type: "script",
    parameters: ["episode6.txt", null, ["space_balls"]],
    requirements: {
      config: { tapeMode: "off" },
    },
    discordRoleId: "744325174668820550",
    category: "scriptsOrSongs",
    description: "Type out the entire Star Wars Episode 6 script with punctuation while watching the movie simultaneously.",
  },
  jolly: {
    display: "Jolly",
    autoRole: true,
    type: "script",
    parameters: ["jolly.txt", null, null],
    message: "Minimum 70wpm required.",
    requirements: {
      wpm: { min: 70 },
    },
    discordRoleId: "768497412548329563",
    category: "scriptsOrSongs",
    description: "Type the Jolly script with a minimum of 70 wpm.",
  },
  gottaCatchEmAll: {
    display: "Gotta Catch 'Em All",
    autoRole: true,
    type: "script",
    parameters: ["pokemon.txt", null, null],
    discordRoleId: "767069340599975998",
    category: "scriptsOrSongs",
    description: "Type out the names of all Pokemon.",
  },
  rapGod: {
    display: "Rap God",
    autoRole: true,
    type: "script",
    parameters: ["rapgod.txt", null, null],
    message: "Minimum 85wpm and 90% accuracy required.",
    requirements: {
      wpm: { min: 85 },
      acc: { min: 90 },
      afk: { max: 5 },
    },
    discordRoleId: "743844891045396603",
    category: "scriptsOrSongs",
    description: "Type out the lyrics of Eminem's Rap God at a minimum of 85 WPM and 90% accuracy, including punctuation.",
  },
  navySeal: {
    display: "Navy Seal",
    autoRole: true,
    type: "script",
    parameters: ["navyseal.txt", null, null],
    message: "Minimum 60wpm and 100% accuracy required.",
    requirements: {
      wpm: { min: 60 },
      acc: { exact: 100 },
      afk: { max: 5 },
    },
    discordRoleId: "762345535969165342",
    category: "scriptsOrSongs",
    description: "Type out the Navy Seal copy pasta with 100% accuracy and minimum 60 WPM.",
  },
  littleChef: {
    display: "Little Chef",
    type: "script",
    parameters: ["littlechef.txt", null, null],
    discordRoleId: "763544714028122153",
    category: "scriptsOrSongs",
    description: "Type out the entire Ratatouille script while watching the movie simultaneously.",
  },
  crosstalk: {
    display: "(CROSSTALK)",
    type: "script",
    parameters: ["crosstalk.txt", null, null],
    discordRoleId: "761276009664217129",
    category: "scriptsOrSongs",
    description: "Type out the entire transcript of the first 2020 Presidential Debate.",
  },
  bees: {
    display: "Bees!!!",
    type: "script",
    parameters: ["bees.txt", null, null],
    discordRoleId: "739636003182084307",
    category: "scriptsOrSongs",
    description: "Type out the entire Bee Movie script while watching the movie simultaneously.",
  },
  getOffMySwamp: {
    display: "Get Off My Swamp",
    type: "script",
    parameters: ["shrek.txt", null, null],
    discordRoleId: "757346966987342026",
    category: "scriptsOrSongs",
    description: "Type out the entire Shrek script with punctuation while watching the movie simultaneously.",
  },
  fiftyShadesOfHell: {
    display: "50 Shades of Hell",
    type: "script",
    parameters: [null, null, null],
    discordRoleId: "751802155119280128",
    category: "scriptsOrSongs",
    description: "Type out your favourite chapter from 50 Shades of Gray.",
  },
  lookAtMeIAmTheDeveloperNow: {
    display: "Look at me. I am the developer now.",
    autoRole: true,
    type: "script",
    parameters: ["sourcecode.txt", null, null],
    discordRoleId: "937358772635074600",
    category: "scriptsOrSongs",
    description: "Type out the entire source code of Monkeytype, as it was in February 2022.",
  },
  beLikeWater: {
    display: "Be Like Water",
    type: "funbox",
    parameters: [["layoutfluid"], "time", 60],
    message: "Remember: You need to achieve at least 50 wpm in each layout.",
    discordRoleId: "740568679485276201",
    category: "funbox",
    description: "Achieve at least 50 WPM in all three layouts in a 60-second time test using the layoutfluid mode. Layouts must be unique (e.g., QWERTY, Colemak, Dvorak).",
  },
  rollercoaster: {
    display: "Rollercoaster",
    autoRole: true,
    type: "funbox",
    parameters: [["round_round_baby"], "time", 3600],
    requirements: {
      time: { min: 3600 },
      funbox: { exact: ["round_round_baby"] },
    },
    discordRoleId: "736032495526740001",
    category: "funbox",
    description: "Complete at least a one-hour test using the round round baby mode.",
  },
  oneHourMirror: {
    display: "ɿoɿɿim ɿυoʜ ɘno",
    autoRole: true,
    type: "funbox",
    parameters: [["mirror"], "time", 3600],
    requirements: {
      time: { min: 3600 },
      funbox: { exact: ["mirror"] },
    },
    discordRoleId: "737385182998429757",
    category: "funbox",
    description: "Complete at least a one-hour test using the mirror mode.",
  },
  chooChoo: {
    display: "Choo choo",
    autoRole: true,
    type: "funbox",
    parameters: [["choo_choo"], "time", 3600],
    requirements: {
      time: { min: 3600 },
      funbox: { exact: ["choo_choo"] },
    },
    discordRoleId: "739306439574683710",
    category: "funbox",
    description: "Complete at least a one-hour test using choo choo mode.",
  },
  mnemonist: {
    display: "Mnemonist",
    type: "funbox",
    parameters: [["memory"], "words", 25, "master"],
    requirements: {
      config: { tapeMode: "off" },
    },
    discordRoleId: "782005606852067328",
    category: "funbox",
    description: "Achieve 100+ WPM with 100% accuracy on a 25-word test using the memory funbox.",
  },
  earfquake: {
    display: "Earfquake",
    autoRole: true,
    type: "funbox",
    parameters: [["earthquake"], "time", 3600],
    requirements: {
      time: { min: 3600 },
      funbox: { exact: ["earthquake"] },
    },
    discordRoleId: "740730587429601291",
    category: "funbox",
    description: "Complete at least a one-hour test using the earthquake funbox mode.",
  },
  simonSez: {
    display: "Simon Sez",
    autoRole: true,
    type: "funbox",
    parameters: [["simon_says"], "time", 3600],
    requirements: {
      time: { min: 3600 },
      funbox: { exact: ["simon_says"] },
    },
    discordRoleId: "742128871825997914",
    category: "funbox",
    description: "Complete at least a one-hour test using the simon says funbox mode.",
  },
  accountant: {
    display: "Accountant",
    autoRole: true,
    type: "funbox",
    parameters: [["58008"], "time", 3600],
    requirements: {
      time: { min: 3600 },
      funbox: { exact: ["58008"] },
    },
    discordRoleId: "743962178821816391",
    category: "funbox",
    description: "Complete at least a one-hour test using the 58008 funbox mode.",
  },
  hidden: {
    display: "Hidden",
    autoRole: true,
    type: "funbox",
    parameters: [["read_ahead"], "time", 60],
    requirements: {
      wpm: { min: 100 },
      time: { min: 60 },
      funbox: { exact: ["read_ahead"] },
      config: { tapeMode: "off" },
    },
    discordRoleId: "782006137742557194",
    category: "funbox",
    description: "Achieve 100+ WPM using the read ahead funbox on a 60-second test.",
  },
  iCanSeeTheFuture: {
    display: "I can see the future",
    autoRole: true,
    type: "funbox",
    parameters: [["read_ahead_hard"], "time", 60],
    requirements: {
      wpm: { min: 100 },
      time: { min: 60 },
      funbox: { exact: ["read_ahead_hard"] },
      config: { tapeMode: "off" },
    },
    discordRoleId: "814877508008411226",
    category: "funbox",
    description: "Achieve 100+ WPM using the read ahead hard funbox on a 60-second test.",
  },
  whatAreWordsAtThisPoint: {
    display: "What are words at this point",
    autoRole: true,
    type: "funbox",
    parameters: [["gibberish"], "time", 3600],
    requirements: {
      time: { min: 60 },
      funbox: { exact: ["gibberish"] },
    },
    discordRoleId: "744209241396740176",
    category: "funbox",
    description: "Complete at least a one-hour test using the gibberish funbox mode.",
  },
  specials: {
    display: "Specials",
    autoRole: true,
    type: "funbox",
    parameters: [["specials"], "time", 3600],
    requirements: {
      time: { min: 60 },
      funbox: { exact: ["specials"] },
    },
    discordRoleId: "744209452714033162",
    category: "funbox",
    description: "Complete at least a one-hour test using the specials funbox mode.",
  },
  aeiou: {
    display: "Aeiou.",
    autoRole: true,
    type: "funbox",
    parameters: [["tts"], "time", 3600],
    requirements: {
      time: { min: 60 },
      funbox: { exact: ["tts"] },
    },
    discordRoleId: "744318102766092362",
    category: "funbox",
    description: "Complete at least a one-hour test using the tts funbox mode.",
  },
  asciiWarrior: {
    display: "ASCII warrior",
    autoRole: true,
    type: "funbox",
    parameters: [["ascii"], "time", 3600],
    requirements: {
      time: { min: 60 },
      funbox: { exact: ["ascii"] },
    },
    discordRoleId: "746142791326760980",
    category: "funbox",
    description: "Complete at least a one-hour test using the ascii funbox mode.",
  },
  iKiNdAlIkEhOwInEfFiCiEnTqWeRtYiS: {
    display: "i KINda LikE HoW inEFFICIeNt QwErtY Is.",
    autoRole: true,
    type: "funbox",
    parameters: [["sPoNgEcAsE"], "time", 3600],
    requirements: {
      time: { min: 60 },
      funbox: { exact: ["sPoNgEcAsE"] },
    },
    discordRoleId: "760999194525171724",
    category: "funbox",
    description: "Complete at least a one-hour test using the randomcase funbox mode.",
  },
  oneNauseousMonkey: {
    display: "One Nauseous Monkey",
    autoRole: true,
    type: "funbox",
    parameters: [["nausea"], "time", 3600],
    requirements: {
      time: { min: 60 },
      funbox: { exact: ["nausea"] },
    },
    discordRoleId: "760930262740631633",
    category: "funbox",
    description: "Complete at least a one-hour test using the nausea funbox mode.",
  },
  thumbWarrior: {
    display: "Thumb Warrior",
    type: "customTime",
    parameters: [3600],
    discordRoleId: "761794585109200906",
    category: "otherChallenges",
    description: "Complete a one-hour test using only your thumbs.",
  },
  mouseWarrior: {
    display: "Mouse warrior",
    type: "customTime",
    parameters: [3600],
    discordRoleId: "744580294442614790",
    category: "otherChallenges",
    description: "Complete a one-hour test using only the on-screen keyboard. Funbox modes are not allowed.",
  },
  mobileWarrior: {
    display: "Mobile warrior",
    type: "customTime",
    parameters: [3600],
    discordRoleId: "744723801526370407",
    category: "otherChallenges",
    description: "Complete a one-hour test on mobile.",
  },
  upsideDown: {
    display: "uʍop ǝpᴉsdn",
    type: "customTime",
    parameters: [60],
    discordRoleId: "782725716114014237",
    category: "otherChallenges",
    description: "Achieve at least 60 WPM on a one-minute test with your keyboard upside down.",
  },
  oneArmedBandit: {
    display: "One armed bandit",
    type: "customWords",
    parameters: [10000],
    discordRoleId: "765919192557682708",
    category: "otherChallenges",
    description: "Complete a one-hour or 10k words test (whichever comes sooner, using an external timer) using a one-handed words list (either left or right) for your layout.",
  },
  englishMaster: {
    display: "English master",
    autoRole: true,
    type: "customTime",
    parameters: [3600],
    requirements: {
      time: { min: 3600 },
      config: { language: "english_10k", punctuation: true, numbers: true },
    },
    discordRoleId: "751166528824672396",
    category: "otherChallenges",
    description: "Complete a one-hour test using English 10k language with punctuation and numbers enabled.",
  },
  footWarrior: {
    display: "Foot Warrior",
    type: "customTime",
    parameters: [3600],
    discordRoleId: "751953592860147822",
    category: "otherChallenges",
    description: "Complete a one-hour test using your feet. Don't ask me why.",
  },
  wingdings: {
    display: "Ten Words of Pain",
    type: "other",
    parameters: [],
    message:
      "Complete a 10-word Master mode test using the Wingdings custom font. No keymap allowed. Minimum 60 WPM and 100% accuracy required.",
    requirements: {
      acc: { exact: 100 },
    },
    discordRoleId: "863192575984140338",
    category: "otherChallenges",
    description: "Complete a 10-word Master mode test using the Wingdings custom font.",
  },
  ultimateMonkeyFlex: {
    display: "Ultimate Monkey Flex",
    parameters: [null, null, null],
    discordRoleId: "768497815496032266",
    category: "champions",
    description: "Have the most champion roles in the server.",
  },
  oneRoleToRuleThemAll: {
    display: "One role to rule them all",
    parameters: [null, null, null],
    discordRoleId: "758784729151176755",
    category: "champions",
    description: "Have the most challenge roles in the server.",
  },
  doYouKnowTheDefinitionOfInsanity: {
    display: "Do You Know The Definition Of Insanity",
    parameters: [null, null, null],
    discordRoleId: "736527448757370880",
    category: "champions",
    description: "Complete the longest typing session in Monkeytype history.",
  },
  oneHourChampion: {
    display: "One Hour Champion",
    parameters: [null, null, null],
    discordRoleId: "728650773503934464",
    category: "champions",
    description: "Achieve the highest WPM in a one-hour test.",
  },
  fluidChampion: {
    display: "Fluid Champion",
    parameters: [null, null, null],
    discordRoleId: "740568718719058041",
    category: "champions",
    description: "Achieve the highest WPM in a 60-second layoutfluid test.",
  },
  accuracyChampion: {
    display: "Accuracy Champion",
    parameters: [null, null, null],
    discordRoleId: "768499906511110235",
    category: "champions",
    description: "Achieve the longest Master mode test.",
  },
  literallyTheFastestPersonHere: {
    display: "Literally The Fastest Person Here",
    parameters: [null, null, null],
    discordRoleId: "984922187385405460",
    category: "champions",
    description: "Achieve 1st place on the time 60 English all-time leaderboard.",
  },
  // fehmer suggested putting it here under the champions section (as its a role obtainable by anyone)
  bananaHoarder: {
    display: "Banana Hoarder",
    parameters: [null, null, null],
    discordRoleId: "773590599227932754",
    category: "champions",
    description: "Achieve 1st place on the banana leaderboard.",
  },
  alpha: {
    display: "A l p h a",
    parameters: [null, null, null],
    discordRoleId: "773590612762034176",
    category: "speed",
    description: "Type the alphabet, with each letter separated by a space and in alphabetical order a b c d e f g h i j k l m n o p q r s t u v w x y z in LESS than 3.37 seconds.",
  },
  blazeIt: {
    display: "Blaze It",
    parameters: [null, null, null],
    discordRoleId: "803650889461006346",
    category: "speed",
    description: "Achieve 420 WPM (can be rounded) by typing weed.",
  },
  burstMaster: {
    display: "Burst Master",
    parameters: [null, null, null],
    discordRoleId: "757330922726096917",
    category: "speed",
    description: "Achieve 200+ WPM on the words 10 mode.",
  },
  burstGod: {
    display: "Burst God",
    parameters: [null, null, null],
    discordRoleId: "757330992821305366",
    category: "speed",
    description: "Achieve 250+ WPM on the words 10 mode.",
  },
  shotgun: {
    display: "Shotgun",
    parameters: [null, null, null],
    discordRoleId: "757331084366184539",
    category: "speed",
    description: "Achieve 300+ WPM on the words 10 mode.",
  },
  nuke: {
    display: "Nuke",
    parameters: [null, null, null],
    discordRoleId: "912522664604758016",
    category: "speed",
    description: "Achieve 350+ WPM on the words 10 mode.",
  },
  orbitalCannon: {
    display: "Orbital Cannon",
    parameters: [null, null, null],
    discordRoleId: "1084094136199684196",
    category: "speed",
    description: "Achieve 400+ WPM on the words 10 mode.",
  },
  marathonSprinter: {
    display: "Marathon Sprinter",
    parameters: [null, null, null],
    discordRoleId: "878715678830510111",
    category: "speed",
    description: "Achieve 200+ WPM on a one-hour test.",
  },
  flawless: {
    display: "Flawless",
    parameters: [null, null, null],
    discordRoleId: "767070815987695637",
    category: "accuracy",
    description: "Complete back-to-back tests in Master Mode: 15, 30, 60, 120 seconds and 10, 25, 50, 100 words. If you fail one, restart from the beginning. Order of modes is up to you.",
  },
  hesBeginningToBelieve: {
    display: "He's beginning to believe",
    parameters: [null, null, null],
    discordRoleId: "979729541096431688",
    category: "accuracy",
    description: "Achieve 100% accuracy in a 2-minute test under specified settings.",
  },
  goldenHands: {
    display: "Golden Hands",
    parameters: [null, null, null],
    discordRoleId: "851096860969795684",
    category: "accuracy",
    description: "Complete a 1-hour Master mode test.",
  },
  fingerBlaster: {
    display: "Finger Blaster",
    parameters: [null, null, null],
    discordRoleId: "787509606992969728",
    category: "otherChallenges",
    description: "Achieve at least 60 WPM using one finger on a 60-second test.",
  },
  whyAreTheWallsMoving: {
    display: "Why are the walls moving?",
    parameters: [null, null, null],
    discordRoleId: "910078947302191114",
    category: "otherChallenges",
    description: "Complete a one-hour test using tape mode and letter mode.",
  },
  stickman: {
    display: "stickman",
    parameters: [null, null, null],
    discordRoleId: "788107449151651890",
    category: "otherChallenges",
    description: "Complete a one-hour test using chopsticks/pencils/pens (you get the idea) with both hands.",
  },
  waveDynamics: {
    display: "Wave Dynamics",
    parameters: [null, null, null],
    discordRoleId: "1443311363794407586",
    category: "otherChallenges",
    description: "Achieve 30 wpm 100% acc on a 60 second test with the raw graph being a perfect wave (to achieve this, type 5 characters in 1 second, pause for 1 second, repeat). Must be completed with random words (time 60 mode). Must include words history in the screenshot.",
  },
  apesTogetherStrong: {
    display: "Apes Together Strong",
    parameters: [null, null, null],
    discordRoleId: "863193901153779713",
    category: "otherChallenges",
    description: "Complete a one-hour test in a Tribe lobby with at least 10 players.",
  },
  apesTogetherStronger: {
    display: "Apes Together Stronger",
    parameters: [null, null, null],
    discordRoleId: "898964842726195220",
    category: "otherChallenges",
    description: "Complete a two-hour test in a Tribe lobby with at least 10 players.",
  },
  apesTogetherInvincible: {
    display: "Apes Together Invincible",
    parameters: [null, null, null],
    discordRoleId: "1367559768746758194",
    category: "otherChallenges",
    description: "Complete a three-hour test in a Tribe lobby with at least 10 players.",
  },
  footBarbarian: {
    display: "Foot Barbarian",
    parameters: [null, null, null],
    discordRoleId: "1025814170962231336",
    category: "otherChallenges",
    description: "Complete a two-hour test using your feet.",
  },
  bigFoot: {
    display: "Big Foot",
    parameters: [null, null, null],
    discordRoleId: "1030531753082900610",
    category: "otherChallenges",
    description: "Complete a three-hour test using your feet.",
  },
  woodPecker: {
    display: "Wood Pecker",
    parameters: [null, null, null],
    discordRoleId: "753724531666845830",
    category: "otherChallenges",
    description: "Complete a 200-word test using only your nose.",
  },
  mrWorldwide: {
    display: "Mr Worldwide",
    parameters: [null, null, null],
    discordRoleId: "762345904279519292",
    category: "otherChallenges",
    description: "Achieve 100 WPM on a 60-second test in 5 different languages (English, English expanded, English 10k and coding languages all count as English which is 1 language).",
  },
  internalMetronome: {
    display: "Internal Metronome",
    parameters: [null, null, null],
    discordRoleId: "934067904884916234",
    category: "otherChallenges",
    description: "Complete a 60-second test (standard English) with a minimum consistency of 90%, 100% accuracy and within 25% of your 60-second personal best.",
  },
  roleCollector: {
    display: "Role Collector",
    parameters: [null, null, null],
    discordRoleId: "739306809554108520",
    category: "roleCount",
    description: "Collect 10 roles.",
  },
  roleEnthusiast: {
    display: "Role Enthusiast",
    parameters: [null, null, null],
    discordRoleId: "753360663656529931",
    category: "roleCount",
    description: "Collect 20 roles.",
  },
  roleAddict: {
    display: "Role Addict",
    parameters: [null, null, null],
    discordRoleId: "758783172833443850",
    category: "roleCount",
    description: "Collect 30 roles.",
  },
  roleOverdose: {
    display: "Role Overdose",
    parameters: [null, null, null],
    discordRoleId: "758783365930811423",
    category: "roleCount",
    description: "Collect 40 roles.",
  },
  roleZombie: {
    display: "Role Zombie",
    parameters: [null, null, null],
    discordRoleId: "762701731993616405",
    category: "roleCount",
    description: "Collect 50 roles.",
  },
  roleOverlord: {
    display: "Role Overlord",
    parameters: [null, null, null],
    discordRoleId: "805519411502514187",
    category: "roleCount",
    description: "Collect 60 roles.",
  },
  roleImp: {
    display: "Role Imp",
    parameters: [null, null, null],
    discordRoleId: "906565521271558214",
    category: "roleCount",
    description: "Collect 70 roles.",
  },
};
