import { type PersonalBests } from "@monkeytype/schemas/shared";

export const USE_MOCK_PB_DATA = true;

export const MOCK_PERSONAL_BESTS: Pick<PersonalBests, "time" | "words"> = {
  time: {
    "15": [
      {
        wpm: 147,
        raw: 152,
        acc: 99.4,
        consistency: 91.8,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 22, 10, 10),
      },
      {
        wpm: 144,
        raw: 149,
        acc: 99.1,
        consistency: 89.5,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 21, 15, 42),
      },
      {
        wpm: 141,
        raw: 146,
        acc: 98.7,
        consistency: 87.3,
        difficulty: "expert",
        language: "german",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 20, 9, 4),
      },
      {
        wpm: 138,
        raw: 143,
        acc: 98.1,
        consistency: 84.9,
        difficulty: "normal",
        language: "french",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 18, 18, 27),
      },
      {
        wpm: 134,
        raw: 139,
        acc: 97.9,
        consistency: 82.6,
        difficulty: "normal",
        language: "spanish",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 17, 8, 56),
      },
      {
        wpm: 131,
        raw: 137,
        acc: 97.2,
        consistency: 80.1,
        difficulty: "normal",
        language: "portuguese",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 16, 21, 33),
      },
      {
        wpm: 128,
        raw: 133,
        acc: 96.8,
        consistency: 78.4,
        difficulty: "normal",
        language: "italian",
        punctuation: false,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 15, 12, 8),
      },
      {
        wpm: 124,
        raw: 129,
        acc: 96.2,
        consistency: 75.2,
        difficulty: "normal",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: true,
        timestamp: Date.UTC(2026, 4, 14, 16, 44),
      },
      {
        wpm: 120,
        raw: 126,
        acc: 95.6,
        consistency: 73.9,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: true,
        timestamp: 0,
      },
      {
        wpm: 116,
        raw: 121,
        acc: 94.8,
        consistency: 70.7,
        difficulty: "normal",
        language: "english",
        punctuation: false,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 11, 11, 18),
      },
    ],
    "30": [
      {
        wpm: 142,
        raw: 147,
        acc: 99.2,
        consistency: 90.9,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 22, 8, 15),
      },
      {
        wpm: 139,
        raw: 144,
        acc: 98.8,
        consistency: 88.2,
        difficulty: "expert",
        language: "german",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 21, 13, 3),
      },
      {
        wpm: 136,
        raw: 141,
        acc: 98.4,
        consistency: 86.5,
        difficulty: "expert",
        language: "english",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 20, 17, 25),
      },
      {
        wpm: 132,
        raw: 138,
        acc: 97.9,
        consistency: 83.4,
        difficulty: "normal",
        language: "french",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 18, 10, 59),
      },
      {
        wpm: 129,
        raw: 135,
        acc: 97.1,
        consistency: 81.2,
        difficulty: "normal",
        language: "spanish",
        punctuation: false,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 17, 19, 10),
      },
      {
        wpm: 125,
        raw: 130,
        acc: 96.7,
        consistency: 78.7,
        difficulty: "normal",
        language: "russian",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 16, 22, 6),
      },
      {
        wpm: 121,
        raw: 126,
        acc: 95.9,
        consistency: 75.8,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: true,
        timestamp: 0,
      },
      {
        wpm: 117,
        raw: 123,
        acc: 95.1,
        consistency: 72.1,
        difficulty: "normal",
        language: "english",
        punctuation: false,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 13, 7, 40),
      },
    ],
    "60": [
      {
        wpm: 133,
        raw: 138,
        acc: 98.6,
        consistency: 87.1,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 20, 6, 50),
      },
      {
        wpm: 129,
        raw: 134,
        acc: 98.2,
        consistency: 84.2,
        difficulty: "expert",
        language: "german",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 18, 14, 11),
      },
      {
        wpm: 125,
        raw: 130,
        acc: 97.5,
        consistency: 80.6,
        difficulty: "normal",
        language: "english",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 16, 9, 29),
      },
      {
        wpm: 121,
        raw: 126,
        acc: 96.9,
        consistency: 77.8,
        difficulty: "normal",
        language: "french",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 15, 20, 13),
      },
      {
        wpm: 117,
        raw: 122,
        acc: 96.3,
        consistency: 74.5,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: true,
        timestamp: 0,
      },
      {
        wpm: 113,
        raw: 119,
        acc: 95.5,
        consistency: 70.8,
        difficulty: "normal",
        language: "spanish",
        punctuation: false,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 12, 17, 54),
      },
    ],
    "120": [
      {
        wpm: 126,
        raw: 130,
        acc: 98.1,
        consistency: 82.9,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 19, 12, 21),
      },
      {
        wpm: 122,
        raw: 127,
        acc: 97.2,
        consistency: 79.4,
        difficulty: "normal",
        language: "german",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 17, 9, 5),
      },
      {
        wpm: 118,
        raw: 123,
        acc: 96.4,
        consistency: 75.7,
        difficulty: "normal",
        language: "english",
        punctuation: false,
        numbers: false,
        lazyMode: true,
        timestamp: Date.UTC(2026, 4, 14, 18, 36),
      },
      {
        wpm: 114,
        raw: 119,
        acc: 95.8,
        consistency: 72.6,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: 0,
      },
    ],
  },
  words: {
    "10": [
      {
        wpm: 151,
        raw: 156,
        acc: 99.5,
        consistency: 92.4,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 22, 11, 4),
      },
      {
        wpm: 147,
        raw: 152,
        acc: 99.1,
        consistency: 89.8,
        difficulty: "expert",
        language: "german",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 21, 16, 55),
      },
      {
        wpm: 143,
        raw: 148,
        acc: 98.7,
        consistency: 87.2,
        difficulty: "expert",
        language: "french",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 20, 8, 22),
      },
      {
        wpm: 139,
        raw: 144,
        acc: 98.3,
        consistency: 84.6,
        difficulty: "normal",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 19, 20, 9),
      },
      {
        wpm: 134,
        raw: 139,
        acc: 97.8,
        consistency: 81.3,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: true,
        timestamp: 0,
      },
      {
        wpm: 129,
        raw: 135,
        acc: 96.9,
        consistency: 77.5,
        difficulty: "normal",
        language: "spanish",
        punctuation: false,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 15, 13, 40),
      },
    ],
    "25": [
      {
        wpm: 145,
        raw: 150,
        acc: 99.3,
        consistency: 90.6,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 22, 7, 48),
      },
      {
        wpm: 141,
        raw: 146,
        acc: 98.9,
        consistency: 88.3,
        difficulty: "expert",
        language: "german",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 20, 14, 6),
      },
      {
        wpm: 137,
        raw: 142,
        acc: 98.2,
        consistency: 84.8,
        difficulty: "normal",
        language: "french",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 18, 10, 50),
      },
      {
        wpm: 132,
        raw: 137,
        acc: 97.4,
        consistency: 80.7,
        difficulty: "normal",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 16, 18, 18),
      },
      {
        wpm: 128,
        raw: 133,
        acc: 96.6,
        consistency: 76.4,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: true,
        timestamp: 0,
      },
    ],
    "50": [
      {
        wpm: 138,
        raw: 143,
        acc: 98.8,
        consistency: 86.1,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 19, 9, 12),
      },
      {
        wpm: 133,
        raw: 138,
        acc: 97.9,
        consistency: 82.2,
        difficulty: "normal",
        language: "german",
        punctuation: true,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 17, 21, 41),
      },
      {
        wpm: 129,
        raw: 134,
        acc: 97.1,
        consistency: 78.9,
        difficulty: "normal",
        language: "english",
        punctuation: false,
        numbers: false,
        lazyMode: true,
        timestamp: Date.UTC(2026, 4, 15, 11, 27),
      },
      {
        wpm: 124,
        raw: 130,
        acc: 96.1,
        consistency: 74.6,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: 0,
      },
    ],
    "100": [
      {
        wpm: 131,
        raw: 136,
        acc: 98.1,
        consistency: 81.8,
        difficulty: "expert",
        language: "english",
        punctuation: true,
        numbers: false,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 18, 7, 17),
      },
      {
        wpm: 126,
        raw: 131,
        acc: 97.2,
        consistency: 77.6,
        difficulty: "normal",
        language: "french",
        punctuation: false,
        numbers: true,
        lazyMode: false,
        timestamp: Date.UTC(2026, 4, 14, 19, 58),
      },
      {
        wpm: 121,
        raw: 126,
        acc: 96.4,
        consistency: 73.2,
        difficulty: "normal",
        language: undefined,
        punctuation: false,
        numbers: false,
        lazyMode: true,
        timestamp: 0,
      },
    ],
  },
};
