const _ = require("lodash");
const joi = require("joi");

const LAYOUTS = [
  "qwerty",
  "dvorak",
  "colemak",
  "colemak_dh",
  "colemak_dh_wide",
  "colemak_dhk",
  "colemak_dh_matrix",
  "colemak_dh_iso",
  "colemak_dhk_iso",
  "colemak_dhv",
  "qwertz",
  "workman",
  "turkish_f",
  "MTGAP_ASRT",
  "norman",
  "halmak",
  "QGMLWB",
  "QGMLWY",
  "qwpr",
  "spanish_qwerty",
  "latam_qwerty",
  "prog_dvorak",
  "german_dvorak",
  "spanish_dvorak",
  "dvorak_L",
  "dvorak_R",
  "azerty",
  "bepo",
  "alpha",
  "handsdown",
  "handsdown_alt",
  "typehack",
  "MTGAP",
  "MTGAP_full",
  "ina",
  "soul",
  "niro",
  "JCUKEN",
  "Diktor",
  "Diktor_VoronovMod",
  "Redaktor",
  "JUIYAF",
  "Zubachev",
  "ISRT",
  "ISRT_Angle",
  "colemak_Qix",
  "colemak_Qi",
  "colemaQ",
  "colemaQ_F",
  "engram",
  "semimak",
  "semimak_jq",
  "boo",
  "boo_mangle",
  "APT",
  "APT_angle",
  "thai_kedmanee",
  "thai_pattachote",
  "thai_manoonchai",
  "persian_standard",
  "arabic",
  "arabic_mac",
  "brasileiro_nativo",
  "Foalmak",
  "quartz",
  "arensito",
  "ARTS",
  "beakl_15",
  "beakl_19",
  "beakl_19_bis",
  "capewell_dvorak",
  "colman",
  "heart",
  "klauser",
  "oneproduct",
  "pine",
  "real",
  "rolll",
  "stndc",
  "three",
  "uciea",
  "asset",
  "dwarf",
  "flaw",
  "whorf",
  "whorf6",
  "sertain",
  "ctgap",
  "ctgap_3",
  "octa8",
];

const LAYOUTS_SET = new Set(LAYOUTS);

const FUNBOX_MODES = [
  "nausea",
  "round_round_baby",
  "simon_says",
  "mirror",
  "tts",
  "choo_choo",
  "arrows",
  "rAnDoMcAsE",
  "capitals",
  "layoutfluid",
  "earthquake",
  "space_balls",
  "gibberish",
  "58008",
  "ascii",
  "specials",
  "plus_one",
  "plus_two",
  "read_ahead_easy",
  "read_ahead",
  "read_ahead_hard",
  "memory",
  "nospace",
  "poetry",
  "wikipedia",
  "weakspot",
  "pseudolang",
];

const CARET_STYLES = [
  "off",
  "default",
  "underline",
  "outline",
  "block",
  "carrot",
  "banana",
];

const CONFIG_SCHEMA = joi.object({
  theme: joi.string(),
  customTheme: joi.boolean(),
  customThemeColors: joi
    .array()
    .items(joi.string().pattern(/^#[A-Fa-f0-9]{6}$/))
    .length(9),
  favThemes: joi.array().items(joi.string()),
  showKeyTips: joi.boolean(),
  showLiveWpm: joi.boolean(),
  showTimerProgress: joi.boolean(),
  smoothCaret: joi.boolean(),
  quickTab: joi.boolean(),
  punctuation: joi.boolean(),
  numbers: joi.boolean(),
  words: joi.number().min(0),
  time: joi.number().min(0),
  mode: joi.string().valid("time", "words", "quote", "zen", "custom"),
  quoteLength: joi.array().items(joi.number().min(0).max(3)).min(1).max(4),
  language: joi.string(),
  fontSize: joi.number().valid(1, 125, 15, 2, 3, 4),
  freedomMode: joi.boolean(),
  resultFilters: joi.any(),
  difficulty: joi.string().valid("normal", "expert", "master"),
  blindMode: joi.boolean(),
  quickEnd: joi.boolean(),
  caretStyle: joi.string().valid(...CARET_STYLES),
  paceCaretStyle: joi.string().valid(...CARET_STYLES),
  flipTestColors: joi.boolean(),
  layout: joi.string().valid("default", ...LAYOUTS),
  funbox: joi.string().valid("none", ...FUNBOX_MODES),
  confidenceMode: joi.string().valid("off", "on", "max"),
  indicateTypos: joi.boolean(),
  timerStyle: joi.string().valid("bar", "text", "mini"),
  colorfulMode: joi.boolean(),
  randomTheme: joi.string().valid("off", "on", "favorite", "light", "dark"),
  timerColor: joi.string().valid("black", "sub", "text", "main"),
  timerOpacity: joi.number().valid(0.25, 0.5, 0.75, 1),
  stopOnError: joi.string().valid("off", "word", "letter"),
  showAllLines: joi.boolean(),
  keymapMode: joi.string().valid("off", "static", "react", "next"),
  keymapStyle: joi
    .string()
    .valid("staggered", "alice", "matrix", "split", "split_matrix"),
  keymapLegendStyle: joi.string().valid("lowercase", "uppercase", "blank"),
  keymapLayout: joi.string().valid("overrideSync", ...LAYOUTS),
  fontFamily: joi.string(),
  smoothLineScroll: joi.boolean(),
  alwaysShowDecimalPlaces: joi.boolean(),
  alwaysShowWordsHistory: joi.boolean(),
  singleListCommandLine: joi.string().valid("manual", "on"),
  capsLockWarning: joi.boolean(),
  playSoundOnError: joi.boolean(),
  playSoundOnClick: joi.string().valid("off", ..._.range(1, 8).map(_.toString)),
  soundVolume: joi.string().valid("0.1", "0.5", "1.0"),
  startGraphsAtZero: joi.boolean(),
  swapEscAndTab: joi.boolean(),
  showOutOfFocusWarning: joi.boolean(),
  paceCaret: joi.string().valid("off", "average", "pb", "custom"),
  paceCaretCustomSpeed: joi.number().min(0),
  repeatedPace: joi.boolean(),
  pageWidth: joi.string().valid("100", "125", "150", "200", "max"),
  chartAccuracy: joi.boolean(),
  chartStyle: joi.string().valid("line", "scatter"),
  minWpm: joi.string().valid("off", "custom"),
  minWpmCustomSpeed: joi.number().min(0),
  highlightMode: joi.string().valid("off", "letter", "word"),
  alwaysShowCPM: joi.boolean(),
  enableAds: joi.string().valid("off", "on", "max"),
  hideExtraLetters: joi.boolean(),
  strictSpace: joi.boolean(),
  minAcc: joi.string().valid("off", "custom"),
  minAccCustom: joi.number().min(0),
  showLiveAcc: joi.boolean(),
  showLiveBurst: joi.boolean(),
  monkey: joi.boolean(),
  repeatQuotes: joi.string().valid("off", "typing"),
  oppositeShiftMode: joi.string().valid("off", "on", "keymap"),
  customBackground: joi.string().uri().allow(""),
  customBackgroundSize: joi.string().valid("cover", "contain", "max"),
  customBackgroundFilter: joi.array().items(joi.number()),
  customLayoutfluid: joi.string().custom((layouts, helpers) => {
    const separateLayouts = layouts.split("#");
    const allLayoutsValid = separateLayouts.every((layout) =>
      LAYOUTS_SET.has(layout)
    );

    if (!allLayoutsValid) {
      return helpers.error("any.invalid");
    }

    return layouts;
  }),
  monkeyPowerLevel: joi.string().valid("off", "1", "2", "3", "4"),
  minBurst: joi.string().valid("off", "fixed", "flex"),
  minBurstCustomSpeed: joi.number().min(0),
  burstHeatmap: joi.boolean(),
  britishEnglish: joi.boolean(),
  lazyMode: joi.boolean(),
});

module.exports = CONFIG_SCHEMA;
