#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm
export NVM_DIR="$HOME/.nvm"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  # nvm not available, quietly exit
  exit 0
fi
. "$NVM_DIR/nvm.sh"


nvm install
pnpm i