#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ $(git branch --no-color | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/') = "master" ] && [ $(git remote get-url origin) = "https://github.com/monkeytypegame/monkeytype" ]; then
  echo "Running tests before pushing to master..."
  npm run test
  if [ $? -ne 0 ]; then
    echo "Tests failed, aborting push."
    exit 1
  fi
fi