name: Write label on PR/issue

permissions:
  pull-requests: write
  issues: write

on:
  workflow_run:
    workflows: [Check labels to update]
    types: [completed]

jobs:
  write-labels:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read json file
        run: echo "LABELS_JSON=`cat ./labels/write-labels.json`" >> $GITHUB_ENV

      - name: Populate variables from JSON values
        run: |
          echo "PR_NUM=${{ fromJSON(env.LABELS_JSON).pr_num }}" >> $GITHUB_ENV
          echo "ADD_LABELS=${{ fromJSON(env.LABELS_JSON).add_labels }}" >> $GITHUB_ENV
          echo "REMOVE_LABELS=${{ fromJSON(env.LABELS_JSON).remove_labels }}" >> $GITHUB_ENV

      - name: Add/remove labels
        if: env.ADD_LABELS != '' || env.REMOVE_LABELS != ''
        uses: PauMAVA/add-remove-label-action@v1.0.3
        with:
          issue_number: ${{ env.PR_NUM }}
          add: ${{ env.ADD_LABELS }}
          remove: ${{ env.REMOVE_LABELS }}
