"use strict";
exports.__esModule = true;
exports.regexProfanities = exports.profanities = void 0;
var lodash_1 = require("lodash");
exports.profanities = [
  "ahole", 
  "amcik", 
  "andskota", 
  "anus", 
  "arschloch", 
  "arse", 
  "ash0le", 
  "asholes", 
  "assh0le", 
  "asshole", 
  "assholz", 
  "assrammer", 
  "asswipe", 
  "ayir", 
  "azzhole", 
  "b!+ch", 
  "b!tch", 
  "b00b", 
  "b17ch", 
  "b1tch", 
  "bassterds", 
  "bastard",  
  "basterds", 
  "basterdz", 
  "bi+ch", 
  "bi7ch", 
  "biatch", 
  "bitch", 
  "bitly", 
  "blow job", 
  "blowjob", 
  "boffing", 
  "boiolas", 
  "bollock", 
  "boobs", 
  "breasts", 
  "buceta", 
  "butt-pirate", 
  "butthole", 
  "buttwipe", 
  "c0ck", 
  "c0k", 
  "cabron", 
  "carpet muncher", 
  "cawk",  
  "cazzo", 
  "chink", 
  "chraa", 
  "chuj", 
  "cipa", 
  "clit",  
  "cnts", 
  "cntz", 
  "cock", 
  "crap", 
  "cunt",  
  "d4mn", 
  "damn", 
  "daygo", 
  "dego", 
  "dick", 
  "dike", 
  "dild0",  
  "dildo", 
  "dilld0",  
  "dirsa", 
  "dominatricks", 
  "dominatrics", 
  "dominatrix", 
  "dupa", 
  "dyke", 
  "dziwka", 
  "ejackulate", 
  "ejakulate", 
  "ekrem", 
  "ekto", 
  "enculer", 
  "enema", 
  "f u c k", 
  "faen", 
  "fag1t", 
  "faget", 
  "fagg1t", 
  "faggit", 
  "faggot", 
  "fagit", 
  "fags", 
  "fagz", 
  "faig", 
  "faigs", 
  "fanculo", 
  "fanny", 
  "fart", 
  "fatass", 
  "fcuk", 
  "feces", 
  "felcher", 
  "ficken", 
  "fitt", 
  "flikker", 
  "flipping the bird", 
  "foreskin", 
  "fotze", 
  "fuck", 
  "fudge packer", 
  "fukah", 
  "fuken", 
  "fuker", 
  "fukin", 
  "fukk", 
  "fukkah", 
  "fukken", 
  "fukker", 
  "fukkin", 
  "futkretzn", 
  "fux0r", 
  "g00k", 
  "gayboy", 
  "gaygirl", 
  "gayz", 
  "god-damned", 
  "gook", 
  "guiena", 
  "h00r", 
  "h0ar", 
  "h0re", 
  "h4x0r", 
  "helvete", 
  "hoar", 
  "hoer", 
  "honkey", 
  "hoor", 
  "hoore", 
  "hore", 
  "huevon", 
  "injun", 
  "jackoff", 
  "japs", 
  "jerk-off", 
  "jisim", 
  "jism", 
  "jiss", 
  "jizm", 
  "jizz", 
  "kanker", 
  "kawk", 
  "klootzak", 
  "knobz", 
  "knulle", 
  "kraut", 
  "kuksuger", 
  "kunt", 
  "kurac", 
  "kurwa", 
  "kusi", 
  "kyrpa", 
  "l3i+ch", 
  "l3itch", 
  "lesbo", 
  "lezzian", 
  "lipshits", 
  "lipshitz", 
  "mamhoon", 
  "masochist", 
  "masokist", 
  "massterbait", 
  "masstrbait", 
  "masstrbate", 
  "masterbaiter", 
  "masterbat", 
  "masturbat", 
  "merd", 
  "mibun", 
  "miodec", 
  "mofo", 
  "monkleigh",  
  "mouliewop", 
  "muie", 
  "mulkku", 
  "muschi", 
  "n1gr", 
  "nastt", 
  "nazi",  
  "nepesaurio", 
  "ni99a", 
  "ni99er", 
  "niga", 
  "niger", 
  "nigga",  
  "nigger",  
  "nigur;", 
  "niiger;", 
  "niigr;", 
  "niqqa", 
  "niqqer", 
  "nutsack", 
  "orafis", 
  "orgasim;", 
  "orgasm", 
  "orgasum",
  "oriface", 
  "orifice", 
  "orifiss", 
  "orospu", 
  "p0rn", 
  "packi", 
  "packie", 
  "packy", 
  "paki", 
  "pakie", 
  "paky", 
  "paska", 
  "pecker", 
  "peeenus", 
  "peenus", 
  "peinus", 
  "pen1s", 
  "penas", 
  "penis", 
  "penus", 
  "penuus", 
  "perse", 
  "phuck", 
  "phuk", 
  "phuker", 
  "phukker", 
  "picka", 
  "pierdol", 
  "pillu", 
  "pimmel", 
  "pimpis", 
  "piss", 
  "pizda", 
  "poonani", 
  "poontsee", 
  "porn", 
  "pr0n",
  "pr1c",  
  "pr1k", 
  "preteen", 
  "pula", 
  "pule", 
  "pusse", 
  "pussee", 
  "pussy", 
  "puta", 
  "puto", 
  "puuke", 
  "puuker", 
  "qahbeh", 
  "queef", 
  "qweers", 
  "qweerz", 
  "qweir", 
  "rautenberg", 
  "recktum", 
  "rectum", 
  "retard", 
  "s.o.b.", 
  "sadist", 
  "scank", 
  "schaffer", 
  "scheiss", 
  "schlampe", 
  "schlong", 
  "schmuck", 
  "scrotum", 
  "semen", 
  "sexy", 
  "sh!+", 
  "sh!t", 
  "sh1t", 
  "sharmuta", 
  "sharmute", 
  "shemale", 
  "shi+", 
  "shipal", 
  "shit",  
  "shiz", 
  "shyt", 
  "skanck", 
  "skank", 
  "skribz", 
  "skurwysyn", 
  "slut", 
  "smut", 
  "son-of-a-bitch",
  "sphencter", 
  "spic", 
  "spierdalaj", 
  "splooge", 
  "suka", 
  "teets", 
  "teez",
  "testical", 
  "testicle", 
  "tits", 
  "titt", 
  "turd", 
  "twat", 
  "va1jina", 
  "vag1na", 
  "vagiina", 
  "vagina", 
  "vaj1na", 
  "vajina", 
  "vittu", 
  "vullva", 
  "vulva", 
  "wank", 
  "wetback", 
  "wh00r", 
  "wh0re", 
  "whoar", 
  "whore", 
  "wichser", 
  "xrated", 
  "zabourah"
];

//Subset of kaggle dataset https://www.kaggle.com/datasets/mathurinache/the-obscenity-list?resource=download
let bad_names = [
  "@sshole",
  "4skin",
  "anal hore",
  "apeshit",
  "arse-bandits",
  "assfk",
  "azzhole",
  "b1tchees",
  "bastinado",
  "blowjob",
  "c00nies",
  "cockh3ad",
  "cuntlicker",
  "dick sucker",
  "f@ck",
  "fckedup",
  "fkbny",
  "fuccs",
  "fucking me",
  "fudgepackershitter",
  "goddamn mothafuckers",
  "jackasss",
  "knobead",
  "m0thafucker",
  "mfckers",
  "octopussy",
  "pedos",
  "phukeds",
  "r3tard",
  "sh1tfuck",
  "slut hole",
  "twatface",
  "wh0r3",
];

//Subset of kaggle dataset https://www.kaggle.com/datasets/colinmorris/reddit-usernames
let valid_names = [
  "Partypooper009",
  "idiociest",
  "whatisshappen",
  "dejavu21",
  "Gulf_Of_Bietanu",
  "Danger_Knight",
  "Coolnaise",
  "newbikesong",
  "ineedachange82",
  "mexicanstandofficer",
  "DocWanky",
  "bustedbyamazon",
  "s00p3rnaut",
  "bigHodey",
  "laregacobade",
  "Dr_Zurkon",
  "sissysamurai",
  "Conman_Khan",
  "windofadream",
  "blad3s0fgl0ry",
  "FeelsNoMore",
  "farteryhr",
];

function inRange(value, min, max) {
    return value >= min && value <= max;
  }

  const VALID_NAME_PATTERN = /^[\da-zA-Z_.-]+$/;

  function isUsernameValid(name) {
    if (lodash_1.isNil(name) || !inRange(name.length, 1, 16)) {
      return false;
    }
  
    const normalizedName = name.toLowerCase();
  
    const beginsWithPeriod = /^\..*/.test(normalizedName);
    if (beginsWithPeriod) {
      return false;
    }
  
    const isProfanity = exports.profanities.find((profanity) =>
      normalizedName.includes(profanity)
    );
    if (isProfanity) {
      return false;
    }
  
    return VALID_NAME_PATTERN.test(name);
  }

// eslint-disable-next-line no-undef
let false_negatives = 0;
for (let i = 0; i < bad_names.length; ++i) {
  if (isUsernameValid(bad_names[i])) {
    false_negatives += 1;
  }
}
console.log("False negative rate:", false_negatives / bad_names.length);
let false_positives = 0;
for (let i = 0; i < valid_names.length; ++i) {
  if (!isUsernameValid(valid_names[i])) {
    false_positives += 1;
  }
}
console.log("False positive rate:", false_positives / valid_names.length);
